baseurl = "https://koyogakuin.github.io/butsuri/"
title = "甲陽学院 高等学校 物理部(新)"
canonifyurls = true
paginate = 10
languageCode = "ja-jp"
copyright = "Code released under the Apache 2.0 license."
googleAnalytics = "UA-117865841-1" # delete or comment to disable Google Analytics JS generation
disqusShortname = "jia-yang-xue-yuan-wu-li-bu" #delete or comment to disable Disqus comments
hasCJKLanguage = "true"

[author]
  name = "T.H."

[params]
  DateForm = "2006年1月2日"#変えるな絶対！！呪文やこれは！！
  Description = "Koyo Gakuin High School Physics Club"
  Author = "H﨑"
  email = "koyobutsuri@gmail.com"
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post

#[[params.social]]
#  title = "twitter"
#  url = "https://twitter.com/humboldtux"
[[params.social]]
  title = "github"
  url = "https://github.com/koyogakuin/"

[[menu.main]]
  name = "ホーム"
  url = "/"
  weight = -500

[[menu.main]]
  name = "活動記録"
  url = "/post/"
  weight = -400

[[menu.main]]
  name = "部員紹介"
  url = "/page/部員紹介/"
  weight = -300

[[menu.main]]
  name = "バックナンバー"
  url = "/page/バックナンバー/"
  weight = -200

[[menu.main]]
  name = "その他"
  url = "/page/その他/"
  weight = -100
