baseurl = "https://koyogakuin.github.io/butsuri/"
title = "Koyo Physics Club"
canonifyurls = true
paginate = 10
languageCode = "ja-jp"
copyright = "Code released under the Apache 2.0 license."
googleAnalytics = "" # delete or comment to disable Google Analytics JS generation
disqusShortname = "" #delete or comment to disable Disqus comments

[author]
  name = "T.H."

[params]
  DateForm = "Mon, Jan 2, 2006"#変えるな絶対！！呪文やこれは！！
  Description = "Koyo Gakuin High School Physics Club"
  Author = "T.H. & S.H."
  email = "koyobutsuri@gmail.com"
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post

#[[params.social]]
#  title = "twitter"
#  url = "https://twitter.com/humboldtux"
[[params.social]]
  title = "github"
  url = "https://github.com/koyogakuin/"

[[menu.main]]
  name = "ホーム"
  url = "/"
  weight = -500

[[menu.main]]
  name = "活動記録"
  url = "/post/"
  weight = -400

[[menu.main]]
  name = "部員紹介"
  url = "/page/部員紹介/"
  weight = -300

[[menu.main]]
  name = "部誌のバックナンバー"
  url = "/page/バックナンバー/"
  weight = -200

[[menu.main]]
  name = "その他"
  url = "/page/その他/"
  weight = -100
